services:
  db:
    image: postgres:15
    container_name: health-db
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - docker.env.filename
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: