"""Add UploadedFile model and link to Observation

Revision ID: 59efe8c1486d
Revises: 9bed0238f5b8
Create Date: 2025-04-15 11:05:55.176541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59efe8c1486d'
down_revision: Union[str, None] = '9bed0238f5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.add_column('observations', sa.Column('metric', sa.String(), nullable=True))
    op.add_column('observations', sa.Column('value', sa.Float(), nullable=True))

    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE observations SET metric = 'hb', value = hb WHERE hb IS NOT NULL")
    )

    op.drop_column('observations', 'hb')

    op.add_column('observations', sa.Column('file_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'observations', 'uploaded_files', ['file_id'], ['id'])

    # Step 4: Make new columns NOT NULL
    op.alter_column("observations", "metric", nullable=False)
    op.alter_column("observations", "value", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('hb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE observations SET hb = value WHERE metric = 'hb'")
    )
    conn.execute(
        sa.text("DELETE FROM observations WHERE metric != 'hb'")
    )
    op.drop_constraint('observations_file_id_fkey', 'observations', type_='foreignkey')
    op.drop_column('observations', 'file_id')
    op.drop_column('observations', 'value')
    op.drop_column('observations', 'metric')
    op.drop_table('uploaded_files')

    op.alter_column("observations", "hb", nullable=False)
    # ### end Alembic commands ###