"""Add user_id in Observation

Revision ID: 9bed0238f5b8
Revises: a2375d5f3538
Create Date: 2025-04-10 17:58:56.478794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bed0238f5b8'
down_revision: Union[str, None] = 'a2375d5f3538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'observations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_column('observations', 'user_id')
    # ### end Alembic commands ###